name: Build APK

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release Name'
        required: false
        default: 'build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Rename APK
      run: |
        mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{ github.event.inputs.release_name }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.inputs.release_name }}
        path: build/app/outputs/flutter-apk/${{ github.event.inputs.release_name }}.apk
